{% set version = "1.38.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mirt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mirt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mirt/mirt_{{ version }}.tar.gz
  sha256: b256e333cbc2e4763bb79bbcd739c04fbcef535125bb80a90e20b120a7b38f88

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-deriv
    - r-gparotation
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-dcurver
    - r-gridextra
    - r-lattice
    - r-mgcv
    - r-pbapply >=1.3_0
    - r-vegan
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-deriv
    - r-gparotation
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-dcurver
    - r-gridextra
    - r-lattice
    - r-mgcv
    - r-pbapply >=1.3_0
    - r-vegan

test:
  commands:
    - $R -e "library('mirt')"           # [not win]
    - "\"%R%\" -e \"library('mirt')\""  # [win]

about:
  home: https://github.com/philchalmers/mirt, https://github.com/philchalmers/mirt/wiki, https://groups.google.com/forum/#!forum/mirt-package
  license: GPL-3.0-or-later
  summary: Analysis of dichotomous and polytomous response data using unidimensional and multidimensional latent trait models under the Item Response Theory paradigm (Chalmers (2012) <doi:10.18637/jss.v048.i06>).  Exploratory and confirmatory models can be estimated with quadrature (EM)  or stochastic (MHRM) methods. Confirmatory
    bi-factor and two-tier analyses are available for modeling item testlets. Multiple group analysis and mixed effects designs also are available for detecting differential item and test functioning as well as modeling item and person covariates. Finally, latent class models such as the DINA, DINO, multidimensional latent
    class, and several other discrete latent variable models, including mixture and zero-inflated response models,  are supported.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mirt
# Version: 1.30
# Type: Package
# Title: Multidimensional Item Response Theory
# Authors@R: c( person("Phil", family="Chalmers", email = "rphilip.chalmers@gmail.com", role = c("aut", "cre", "cph")), person("Joshua", family="Pritikin", role=c('ctb')), person("Alexander", family="Robitzsch", role=c('ctb')), person("Mateusz", family="Zoltak", role=c('ctb')), person("KwonHyun", family="Kim", role=c('ctb')), person("Carl F.", family="Falk", role=c('ctb')), person("Adam", family="Meade", role=c('ctb')), person("Lennart", family="Schneider", role=c('ctb')), person("David", family="King", role=c('ctb')), person("Chen-Wei", family="Liu", role=c('ctb')), person("Ogreden", family="Oguzhan", role=c('ctb')))
# Description: Analysis of dichotomous and polytomous response data using unidimensional and multidimensional latent trait models under the Item Response Theory paradigm (Chalmers (2012) <doi:10.18637/jss.v048.i06>).  Exploratory and confirmatory models can be estimated with quadrature (EM)  or stochastic (MHRM) methods. Confirmatory bi-factor and two-tier analyses are available for modeling item testlets. Multiple group analysis and mixed effects designs also are available for detecting differential item and test functioning as well as modeling item and person covariates. Finally, latent class models such as the DINA, DINO, multidimensional latent class, and several other discrete latent variable models, including mixture and zero-inflated response models,  are supported.
# VignetteBuilder: knitr
# Depends: stats, R (>= 3.1.0), stats4, lattice, methods
# Imports: GPArotation, Rcpp, mgcv, vegan, Deriv, splines, dcurver
# Suggests: boot, latticeExtra, directlabels, shiny, knitr, Rsolnp, nloptr, sirt, mirtCAT
# ByteCompile: yes
# LazyLoad: yes
# LazyData: yes
# LinkingTo: Rcpp, RcppArmadillo
# License: GPL (>= 3)
# Repository: CRAN
# Maintainer: Phil Chalmers <rphilip.chalmers@gmail.com>
# URL: https://github.com/philchalmers/mirt, https://github.com/philchalmers/mirt/wiki, https://groups.google.com/forum/#!forum/mirt-package
# BugReports: https://github.com/philchalmers/mirt/issues?state=open
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-01-29 03:53:22 UTC; phil
# Author: Phil Chalmers [aut, cre, cph], Joshua Pritikin [ctb], Alexander Robitzsch [ctb], Mateusz Zoltak [ctb], KwonHyun Kim [ctb], Carl F. Falk [ctb], Adam Meade [ctb], Lennart Schneider [ctb], David King [ctb], Chen-Wei Liu [ctb], Ogreden Oguzhan [ctb]
# Date/Publication: 2019-01-29 09:10:03 UTC
