{% set version = "1.39" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mirt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mirt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mirt/mirt_{{ version }}.tar.gz
  sha256: 79d2e29a17a8c295d433d54c06d757e1a0b78a8034069bccf35828de99328173

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-dcurver
    - r-deriv
    - r-gparotation
    - r-gridextra
    - r-lattice
    - r-matrix >=1.5-0
    - r-mgcv
    - r-pbapply >=1.3_0
    - r-rcpp
    - r-rcpparmadillo
    - r-vegan
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-dcurver
    - r-deriv
    - r-gparotation
    - r-gridextra
    - r-lattice
    - r-matrix >=1.5-0
    - r-mgcv
    - r-pbapply >=1.3_0
    - r-rcpp
    - r-rcpparmadillo
    - r-vegan

test:
  commands:
    - $R -e "library('mirt')"           # [not win]
    - "\"%R%\" -e \"library('mirt')\""  # [win]

about:
  home: https://github.com/philchalmers/mirt, https://github.com/philchalmers/mirt/wiki, https://groups.google.com/forum/#!forum/mirt-package
  license: GPL-3.0-or-later
  summary: Analysis of dichotomous and polytomous response data using unidimensional and multidimensional latent trait models under the Item Response Theory paradigm (Chalmers (2012) <doi:10.18637/jss.v048.i06>).  Exploratory and confirmatory models can be estimated with quadrature (EM)  or stochastic (MHRM) methods. Confirmatory
    bi-factor and two-tier analyses are available for modeling item testlets. Multiple group analysis and mixed effects designs also are available for detecting differential item and test functioning as well as modeling item and person covariates. Finally, latent class models such as the DINA, DINO, multidimensional latent
    class, and several other discrete latent variable models, including mixture and zero-inflated response models,  are supported.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
