{% set version = "1.41" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mirt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mirt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mirt/mirt_{{ version }}.tar.gz
  sha256: d01b2d2e8caf0f1569f1db9138839e698e17c46020dfaaab8a5496f649c6a863

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-deriv                    # [build_platform != target_platform]
    - r-dcurver                  # [build_platform != target_platform]
    - r-rcpparmadillo            # [build_platform != target_platform]
    - r-vegan                    # [build_platform != target_platform]
    - r-mgcv                     # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-gridextra                # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - r-gparotation              # [build_platform != target_platform]
    - r-pbapply                  # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('fortran') }}    # [osx and arm64]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-deriv
    - r-gparotation
    - r-matrix >=1.5_0
    - r-rcpp
    - r-rcpparmadillo
    - r-simdesign
    - r-dcurver
    - r-gridextra
    - r-lattice
    - r-mgcv
    - r-pbapply >=1.3_0
    - r-vegan
  run:
    - r-base
    - r-deriv
    - r-gparotation
    - r-matrix >=1.5_0
    - r-rcpp
    - r-rcpparmadillo
    - r-simdesign
    - r-dcurver
    - r-gridextra
    - r-lattice
    - r-mgcv
    - r-pbapply >=1.3_0
    - r-vegan

test:
  commands:
    - $R -e "library('mirt')"           # [not win]
    - "\"%R%\" -e \"library('mirt')\""  # [win]

about:
  home: https://github.com/philchalmers/mirt, https://github.com/philchalmers/mirt/wiki, https://groups.google.com/forum/#!forum/mirt-package
  license: GPL-3.0-or-later
  summary: Analysis of dichotomous and polytomous response data using unidimensional and multidimensional latent trait models under the Item Response Theory paradigm (Chalmers (2012) <doi:10.18637/jss.v048.i06>).  Exploratory and confirmatory models can be estimated with quadrature (EM)  or stochastic (MHRM) methods. Confirmatory
    bi-factor and two-tier analyses are available for modeling item testlets. Multiple group analysis and mixed effects designs also are available for detecting differential item and test functioning as well as modeling item and person covariates. Finally, latent class models such as the DINA, DINO, multidimensional latent
    class, and several other discrete latent variable models, including mixture and zero-inflated response models,  are supported.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
