travis:
  secure:
    BINSTAR_TOKEN: zdIRRzuKpk2DYjvTRlewt8yeGECFae8yQtsPTdOG6wG5lV3t5TUdQyUw/W1y+HkHExkozNN2SFrfRY2vEP/SmKGIeeyCr+0E4P9NEMQDUl80BCtvdWDizcoWC88CRm9z4e2Qb3nTZKKQU9CCn7bK538mBvsG1641cFJQAhnhmBYw4YlbYLMBvgKMlzEQV9L7OoDqpdTb8X2fF9LudxoDQ1xy+5bqCFBhF7VdupUVckEga1XaqxgIDkn6eVXeBOkkXIJC99z1rBLhC+iaX+Jnz9ULQbMPyLnrkQ3NgqALhp0iyoGcoGOfGdZjW1DUOWHI5OuVWf8NIeGOkV8SzVll6guJU/vdHRs4zoqTcPg9VrZUwX2OR2dXukN0Bp9i3xlWmgTv/Ymc3jV5aIYCez3fz9YDV1WXmriqMO+vV+T6KOriDiuVRWAUWa6tUlRvlHE5eTX3buK6VB1PnPo9+psFbLuk2nez7DjsPHEjJ0hqn6hZQKDEJqZU8fbsnqDqiBk2eFDHituQSMmmU980yCToXR1JtpbQzGd7CaH1U42IDDZ0tyoDRD1nw6SIA5UWXtG+zXgiBQPMwI7+ph9rmy0yxXZ2bEB6YGNxL8m2iQ6VxMTtaPTK3hCFtdNeJFP9vltRbQ2wD7LULMWSw9Qkuub6Bsw6UVSRAYKFyKp76jfXpy8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
