travis:
  secure:
    BINSTAR_TOKEN: N4HqmndcXj9jvK+9Mk8wCl14rnvUa3pbsjdPLjrYhN10PhQsGqw6qJgzXqEulx9HTYpq82M/zdNNGdtBht235d/LQN9oCSkLQlO+kfDxOIlvTFxsfPcEaTRXJ6Iq8V1n8lIw+8sQO79Yc0V+2WLjqlbrQ5Z3CPJMxbZ2ErLlO79e6ILcxbXpx7CyaR6lF7lzMvn4wtxF5m4g25LNO17A3qIjxDcdMjkz2Yw8+DY5UQ+J8PFsobWG0ArY3k+NbMoJEi50qqQpIiXdizquN0n2XkHQlreZ+5I/V0MwQXggXNl2/pgE8TNlY8fPNHSOqzAutlMM61t+4buwTfSxE58m7LfM6Tnyg/pj4qJOf59+AGDCjolsn0uOefShi2R+VyvDxWB4OI4WNHW78UI/rZ8fFPsVYyD64lj5yq6bKsbJrvo3bz4tthr/LrFx3fLuOcMSJp8fGrJzb5Ov5bnCzcaZ8tDqpRPcPIf9D60zhJWeswul0naGSViev05L7bnEjYnamtvHhJbWkb6jJyCNWkMdxK+nIe8ZDSyXJWRq/FvHS7MCWgBdUJTmDvnNWD37z2gS4vMbg150xWvqa1CWG/bOb/bdTJk4zmSo8nV+mWlQf+OYiUuX9NTPOrHJlVlDX40U5KXnsX8z8cBecNqFBmpQN9bXPvEXT8o7phmhgfAawbM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
